/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.musicapp;

import java.awt.Desktop;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;


/**
 *
 * @author troydeminico
 */
public class UserView extends javax.swing.JFrame {
    
    //SongHashMap test = new SongHashMap();
    
    Playlist userPlaylist = new Playlist();
    Playlist favPlaylist = new Playlist();
    Playlist userLinks = new Playlist();
    Playlist favLinks = new Playlist();
    Playlist artistList = new Playlist();
    IntList artistCounts = new IntList();
    Playlist userImgs = new Playlist();
    
    ArrayList<Song> mySongs = new ArrayList<>();
    
    private static void openWebpage(String url) {
        try {
            Desktop.getDesktop().browse(new java.net.URI(url));
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    /**
     * Creates new form NewJFrame
     */
    public UserView() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaPList = new javax.swing.JTextArea();
        btnRemove = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        songNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ArtistName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        songName = new javax.swing.JTextField();
        btnArtist = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        songListenNum = new javax.swing.JTextField();
        btnAddFav = new javax.swing.JButton();
        jBtnGenre = new javax.swing.JButton();
        btnListen = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtAreaFav = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        FirstArtist = new javax.swing.JLabel();
        SecondArtist = new javax.swing.JLabel();
        ThirdArtist = new javax.swing.JLabel();
        jLabelFirst = new javax.swing.JLabel();
        jLabelSecond = new javax.swing.JLabel();
        jLabelThird = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtAreaPList.setEditable(false);
        jTxtAreaPList.setColumns(20);
        jTxtAreaPList.setRows(5);
        jScrollPane1.setViewportView(jTxtAreaPList);

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        jLabel2.setText("Song Number");

        songNumber.setText("Song #");
        songNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songNumberActionPerformed(evt);
            }
        });

        jLabel3.setText("Artist");

        ArtistName.setText("Artist name");
        ArtistName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArtistNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Song");

        songName.setText("Song name");

        btnArtist.setText("Artist");
        btnArtist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtistActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        songListenNum.setText("Song #");
        songListenNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                songListenNumActionPerformed(evt);
            }
        });

        btnAddFav.setText("Favorite");
        btnAddFav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFavActionPerformed(evt);
            }
        });

        jBtnGenre.setText("Genre");
        jBtnGenre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenreActionPerformed(evt);
            }
        });

        btnListen.setText("Listen");
        btnListen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(songNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAddFav, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnListen)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAdd)
                                .addGap(31, 31, 31)
                                .addComponent(btnArtist))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnGenre)
                            .addComponent(songListenNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(songNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRemove)
                            .addComponent(btnAddFav))
                        .addGap(18, 18, 18)
                        .addComponent(btnListen)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(songName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ArtistName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnGenre))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnArtist)
                    .addComponent(songListenNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jTabbedPane1.addTab("Home", jPanel1);

        jTxtAreaFav.setEditable(false);
        jTxtAreaFav.setColumns(20);
        jTxtAreaFav.setRows(5);
        jScrollPane2.setViewportView(jTxtAreaFav);

        jLabel5.setText("Favorite Songs");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Favorites", jPanel2);

        jLabel4.setText("Top 3 Artist");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelFirst, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(FirstArtist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(SecondArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(ThirdArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabelSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelThird, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ThirdArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstArtist, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSecond, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelThird, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Top Artist", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String request = songName.getText();
        boolean hasSpace = request.contains(" ");
        if (hasSpace) {
            request = request.replace(" ", "%20");
                    }
       
        Song s = APISearch.getFirstSongInfo(request); 
        mySongs.add(s);
        
        String newSong = s.getSongInfo();
        userPlaylist.addSong(newSong);
        
        // Create a list with the links to the added songs
//        String newLink = APISearch.getSongLink(request);
        String newLink = s.getSongLink();
        String newImg = s.getSongImg();
        
        userLinks.addSong(newLink);
        
        //test.addSong(newSong, newLink);
        
//        String newImg = APISearch.getSongImg(request);
        userImgs.addSong(newImg);
       
        jTxtAreaPList.setText(userPlaylist.toString());
        
//        s = APISearch.getFirstSongArtistInfo(request);
        String newID = s.getArtistID();
        
        int newCount = 1;
        int index = artistList.compareID(newID);
        
        if (index != -1){
            artistCounts.increaseCount(index);
        }
        else{
            artistList.addSong(newID);
            artistCounts.addCount(newCount);
        }
        
        // Get the top 3
            // Set the labels accordingyly;
        Artist a = s.getArtist();
        
//        ImageIcon ii = mySongs.get(0).getArtist().getImage();
//        ImageIcon ii2 = mySongs.get(1).getArtist().getImage();
//        ImageIcon ii3 = mySongs.get(2).getArtist().getImage();
        //ImageIcon ii = a.getImage();
        if (mySongs.size() == 1){
            ImageIcon ii = mySongs.get(0).getArtist().getImage();
            FirstArtist.setIcon(ii);
            jLabelFirst.setText(mySongs.get(0).getArtistName());
        }
        else if (mySongs.size() == 2){
            ImageIcon ii = mySongs.get(0).getArtist().getImage();
            FirstArtist.setIcon(ii);
            jLabelFirst.setText(mySongs.get(0).getArtistName());
            ImageIcon ii2 = mySongs.get(1).getArtist().getImage();
            SecondArtist.setIcon(ii2);
            jLabelSecond.setText(mySongs.get(1).getArtistName());
        }
        if(mySongs.size()>2){
            ImageIcon ii = mySongs.get(0).getArtist().getImage();
            ImageIcon ii2 = mySongs.get(1).getArtist().getImage();
            ImageIcon ii3 = mySongs.get(2).getArtist().getImage();
            FirstArtist.setIcon(ii);
            SecondArtist.setIcon(ii2);
            ThirdArtist.setIcon(ii3);
            jLabelFirst.setText(mySongs.get(0).getArtistName());
            jLabelSecond.setText(mySongs.get(1).getArtistName());
            jLabelThird.setText(mySongs.get(2).getArtistName());
        }
//          To test above code
        //jTxtAreaPList.setText(artistList.toString());
        //jTxtAreaFav.setText(artistCounts.toString());
        //jTxtAreaArtist.setText(Integer.toString(index));
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        String number = songNumber.getText();
        userPlaylist.removeSong(Integer.valueOf(number)-1);
        userLinks.removeSong(Integer.valueOf(number)-1);
        jTxtAreaPList.setText(userPlaylist.toString());
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnListenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListenActionPerformed
//        String request = songName.getText();
//        boolean hasSpace = request.contains(" ");
//        if (hasSpace) {
//            request = request.replace(" ", "%20");
//                    }
//        openWebpage(APISearch.getSongLink(request));
//        

        String number = songNumber.getText();
        openWebpage(userLinks.get(Integer.valueOf(number)-1));
        
    }//GEN-LAST:event_btnListenActionPerformed

    private void songNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songNumberActionPerformed

    private void songListenNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_songListenNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_songListenNumActionPerformed

    private void btnAddFavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFavActionPerformed
        String number = songNumber.getText();
        int number1 = Integer.valueOf(number)-1;
        if (number1 < userPlaylist.getSize() && number1 >= 0){
            favPlaylist.addSong(userPlaylist.get(number1));
            jTxtAreaFav.setText(favPlaylist.toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Invalid number", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnAddFavActionPerformed

    private void ArtistNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArtistNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArtistNameActionPerformed

    private void btnArtistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtistActionPerformed
       APISearch.getArtist("Drake");
        
        
    }//GEN-LAST:event_btnArtistActionPerformed

    private void jBtnGenreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenreActionPerformed
        String request = songName.getText();
        boolean hasSpace = request.contains(" ");
        if (hasSpace) {
            request = request.replace(" ", "%20");
                    }
        APISearch.searchGenre(request);
        String newSong = APISearch.getRandomSongInfo(request); 
        userPlaylist.addSong(newSong);
        // Create a list with the links to the added songs
        String newLink = APISearch.getSongLink(request);
        userLinks.addSong(newLink);
       
        jTxtAreaPList.setText(userPlaylist.toString());
    }//GEN-LAST:event_jBtnGenreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArtistName;
    private javax.swing.JLabel FirstArtist;
    private javax.swing.JLabel SecondArtist;
    private javax.swing.JLabel ThirdArtist;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddFav;
    private javax.swing.JButton btnArtist;
    private javax.swing.JButton btnListen;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jBtnGenre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFirst;
    private javax.swing.JLabel jLabelSecond;
    private javax.swing.JLabel jLabelThird;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea jTxtAreaFav;
    private javax.swing.JTextArea jTxtAreaPList;
    private javax.swing.JTextField songListenNum;
    private javax.swing.JTextField songName;
    private javax.swing.JTextField songNumber;
    // End of variables declaration//GEN-END:variables
}
